/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as QaRouteImport } from './routes/qa'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ZeroDecryptRouteImport } from './routes/zero-decrypt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroDecryptRoute = ZeroDecryptRouteImport.update({
  id: '/zero-decrypt',
  path: '/zero-decrypt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/capabilities': typeof CapabilitiesRoute
  '/qa': typeof QaRoute
  '/security': typeof SecurityRoute
  '/zero-decrypt': typeof ZeroDecryptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/capabilities': typeof CapabilitiesRoute
  '/qa': typeof QaRoute
  '/security': typeof SecurityRoute
  '/zero-decrypt': typeof ZeroDecryptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/capabilities': typeof CapabilitiesRoute
  '/qa': typeof QaRoute
  '/security': typeof SecurityRoute
  '/zero-decrypt': typeof ZeroDecryptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/audit' | '/capabilities' | '/qa' | '/security' | '/zero-decrypt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audit' | '/capabilities' | '/qa' | '/security' | '/zero-decrypt'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/capabilities'
    | '/qa'
    | '/security'
    | '/zero-decrypt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  QaRoute: typeof QaRoute
  SecurityRoute: typeof SecurityRoute
  ZeroDecryptRoute: typeof ZeroDecryptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-decrypt': {
      id: '/zero-decrypt'
      path: '/zero-decrypt'
      fullPath: '/zero-decrypt'
      preLoaderRoute: typeof ZeroDecryptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  QaRoute: QaRoute,
  SecurityRoute: SecurityRoute,
  ZeroDecryptRoute: ZeroDecryptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
